### ISSUE TITLE
[BUG]a error hanpped, when use modbus.json config

### ISSUE THREAD

**Issue by leyoo** [thingsboard/thingsboard-gateway#1140]
**Describe the bug**
a error as bellow:
2023-07-06 20:52:18   Traceback (most recent call last):
2023-07-06 20:52:18   File "/thingsboard_gateway/connectors/modbus/bytes_modbus_uplink_converter.py", line 65, in convert
2023-07-06 20:52:18     decoder = BinaryPayloadDecoder.fromCoils(coils, wordorder=word_endian_order)
2023-07-06 20:52:18 TypeError: BinaryPayloadDecoder.fromCoils() got an unexpected keyword argument 'wordorder'
when i use Modbus Connector - modbus.json and set functionCode = 2, use docker
```
{
    "master": {
        "slaves": [
            {
                "host": "192.168.1.17",
                "port": 502,
                "type": "tcp",
                "method": "socket",
                "timeout": 35,
                "byteOrder": "BIG",
                "wordOrder": "BIG",
                "retries": true,
                "retryOnEmpty": true,
                "retryOnInvalid": true,
                "pollPeriod": 3000,
                "unitId": 1,
                "deviceName": "烟感1",
                "sendDataOnlyOnChange": false,
                "connectAttemptTimeMs": 3000,
                "connectAttemptCount": 5,
                "waitAfterFailedAttemptsMs": 300000,
                "attributes": [],
                "timeseries": [
                    {
                        "tag": "Smoke1",
                        "type": "int",
                        "functionCode": 2,
                        "objectsCount": 1,
                        "address": 0
                    }
                ],
                "attributeUpdates": [],
                "rpc": []
            }
        ]
    }
}
```

**Connector name (If bug in the some connector):**
Modbus Connector - modbus.json

**Error traceback (If available):**
```
Traceback (most recent call last):
2023-07-06 20:50:00   File "/thingsboard_gateway/connectors/modbus/bytes_modbus_uplink_converter.py", line 65, in convert
2023-07-06 20:50:00     decoder = BinaryPayloadDecoder.fromCoils(coils, wordorder=word_endian_order)
2023-07-06 20:50:00 TypeError: BinaryPayloadDecoder.fromCoils() got an unexpected keyword argument 'wordorder'
```

**Versions :**
 - OS: windows 11
 - Thingsboard IoT Gateway version : 3.3
 - Python version: 3.10.12

**Comment by leyoo** [comment]
it's look likes a bug when set fuctionCode =2 in modebus.json config
