### ISSUE TITLE
Modbus connector pulls only the first timeseries or attribute[BUG]

### ISSUE THREAD

**Issue by mrangics** [thingsboard/thingsboard-gateway#1186]
**Describe the bug**
Using ThingsBoard Gateway with Modbus connector, only the first defined registry is read and uploaded to ThingsBoard Server.
In the example below, only the "setTemperature" attribute and the "Temperature" timeseries (telemetry) arrives (being sent) to the server, the second and further tags are neglected.

**Connector name (If bug in the some connector):**
Modbus Connector

**Error traceback (If available):**
```
2023-10-04 21:35:07 Requirement already satisfied: mmh3 in /usr/local/lib/python3.11/site-packages (4.0.1)
2023-10-04 21:35:08 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-10-04 21:35:08 Cannot load GRPC connector!
2023-10-04 21:35:08 2023-10-04 19:35:08 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 196 - Gateway starting...
2023-10-04 21:35:09 2023-10-04 19:35:09 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 201 - ThingsBoard IoT gateway version: 3.4
2023-10-04 21:35:09 2023-10-04 19:35:09 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 184 - Subscribed to *|* with id 1 for device *
2023-10-04 21:35:09 2023-10-04 19:35:09 - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - init_remote_shell - 388 - Remote shell is enabled. Please be carefully with this feature.
2023-10-04 21:35:09 2023-10-04 19:35:09 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import ModbusConnector from /thingsboard_gateway/connectors/modbus.
2023-10-04 21:35:09 2023-10-04 19:35:09 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - __init__ - 54 - Remote Configurator started
2023-10-04 21:35:09 Traceback (most recent call last):
2023-10-04 21:35:09   File "//./thingsboard_gateway/tb_gateway.py", line 41, in <module>
2023-10-04 21:35:09     main()
2023-10-04 21:35:09   File "//./thingsboard_gateway/tb_gateway.py", line 33, in main
2023-10-04 21:35:09     TBGatewayService(path.dirname(path.abspath(__file__)) + '/config/tb_gateway.json'.replace('/', path.sep))
2023-10-04 21:35:09   File "/thingsboard_gateway/gateway/tb_gateway_service.py", line 303, in __init__
2023-10-04 21:35:09     self.__init_remote_configuration()
2023-10-04 21:35:09   File "/thingsboard_gateway/gateway/tb_gateway_service.py", line 533, in __init_remote_configuration
2023-10-04 21:35:09     self.__remote_configurator.send_current_configuration()
2023-10-04 21:35:09   File "/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 149, in send_current_configuration
2023-10-04 21:35:09     {connector['name']: {**connector, 'logLevel': connector['configurationJson']['logLevel'],
2023-10-04 21:35:09                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2023-10-04 21:35:09 KeyError: 'logLevel'
2023-10-04 21:36:19 2023-10-04 19:36:19 - |INFO| - [modbus_connector.py] - modbus_connector - run - 726 - {'deviceName': 'MC6 Thermostat Rangics', 'deviceType': 'default', 'telemetry': [{'Temperature': 258}], 'attributes': [{'SetTemperature': 210}]}
2023-10-04 21:37:30 2023-10-04 19:37:30 - |INFO| - [modbus_connector.py] - modbus_connector - run - 726 - {'deviceName': 'MC6 Thermostat Rangics', 'deviceType': 'default', 'telemetry': [{'Temperature': 258}], 'attributes': [{'SetTemperature': 210}]}
```

**Configuration files**
[tb_gateway.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/12807579/tb_gateway.json.txt)
[modbus_new_1.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/12807580/modbus_new_1.json.txt)

**Versions (please complete the following information):**
 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version 3.4
 - Python version 3.9

**Comment by mrangics** [comment]
This seems to be a device error.
Testing with other devices, it works smooth, multiple registers are read if Mikrotik KNOT used as Modbus RTU - Mobdus TCP Gateway.
