### ISSUE TITLE
Some messages not forewared to thingsboard. Mqtt connection dropping ?

### ISSUE THREAD

**Issue by sebsoft** [thingsboard/thingsboard-gateway#121]
I'm running Gateway (v2.0.4-SNAPSHOT)  and TB (v2.1.1-SNAPSHOT) on the same windows 10 machine.  Using the http extension i post identical messages to http://localhost:9090/uplink/ttn/  .  About 10 out of 50 result in an error.  See below for gateway logs in case of messages which get through and messages which do not arrive at TB.   (Also note that the HTTP response is also rather slow.)

In case of NO error this is found in the gateway log file:

`2018-09-13 11:16:39,043 [http-nio-0.0.0.0-9090-exec-2] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2] Device Connected!
2018-09-13 11:16:39,084 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"device":"mydevid2","type":"mydevid2"}, timestamp=0, topic='v1/gateway/connect'id=cfa0176a-04d4-406e-b79a-0402853197b2, messageId=7}]
2018-09-13 11:16:39,084 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:16:39,086 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:16:39,112 [pool-3-thread-1] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][mydevid2][7] Device connect event is reported to Thingsboard!
2018-09-13 11:16:39,113 [http-nio-0.0.0.0-9090-exec-2] TRACE o.t.g.s.gateway.MqttGatewayService - [mydevid2][8] Updating device attributes: [StringDataEntry{value='0102030405060708'} BasicKvEntry{key='hardware_serial'}]
2018-09-13 11:16:39,121 [http-nio-0.0.0.0-9090-exec-2] TRACE o.t.g.s.gateway.MqttGatewayService - [mydevid2][9] Updating device telemetry: [BasicTsKvEntry{ts=1536830199015, kv=LongDataEntry{value=30} BasicKvEntry{key='counter'}}]
2018-09-13 11:16:40,086 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"mydevid2":{"hardware_serial":"0102030405060708"}}, timestamp=0, topic='v1/gateway/attributes'id=ee77d9e2-5f37-4b9c-b7bc-ce2cff8fddf5, messageId=8}]
2018-09-13 11:16:40,087 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"mydevid2":[{"ts":1536830199015,"values":{"counter":30}}]}, timestamp=0, topic='v1/gateway/telemetry'id=8f48a09c-899e-42a3-ab9c-d32b197d7305, messageId=9}]
2018-09-13 11:16:40,090 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [2] messages are still in progress
2018-09-13 11:16:40,090 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:16:40,150 [pool-3-thread-1] DEBUG o.t.g.s.gateway.MqttGatewayService - [mydevid2][8] Device attributes were delivered!
2018-09-13 11:16:40,150 [pool-3-thread-1] DEBUG o.t.g.s.gateway.MqttGatewayService - [9][mydevid2] Device telemetry published to ThingsBoard!
2018-09-13 11:16:40,151 [http-nio-0.0.0.0-9090-exec-2] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][10] Device Disconnected!
2018-09-13 11:16:41,091 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"device":"mydevid2"}, timestamp=0, topic='v1/gateway/disconnect'id=763f7510-42d0-462a-862a-b8b71fcd24ae, messageId=10}]
2018-09-13 11:16:41,093 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:16:41,093 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:16:41,118 [pool-3-thread-1] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][10] Device disconnect event is delivered!
`

In case of error this is found in the log file:

`2018-09-13 11:17:31,491 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"device":"mydevid2","type":"mydevid2"}, timestamp=0, topic='v1/gateway/connect'id=0f91a0ae-6623-44c7-b129-4f88d0ae1952, messageId=59}]
2018-09-13 11:17:31,491 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:31,492 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:31,493 [pool-3-thread-1] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][mydevid2][59] Device connect event is reported to Thingsboard!
2018-09-13 11:17:31,493 [http-nio-0.0.0.0-9090-exec-5] TRACE o.t.g.s.gateway.MqttGatewayService - [mydevid2][60] Updating device attributes: [StringDataEntry{value='0102030405060708'} BasicKvEntry{key='hardware_serial'}]
2018-09-13 11:17:31,494 [http-nio-0.0.0.0-9090-exec-5] TRACE o.t.g.s.gateway.MqttGatewayService - [mydevid2][61] Updating device telemetry: [BasicTsKvEntry{ts=1536830250563, kv=LongDataEntry{value=30} BasicKvEntry{key='counter'}}]
2018-09-13 11:17:32,493 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"mydevid2":{"hardware_serial":"0102030405060708"}}, timestamp=0, topic='v1/gateway/attributes'id=9a994392-8521-4320-87bc-c53c5e893dd7, messageId=60}]
2018-09-13 11:17:32,496 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"mydevid2":[{"ts":1536830250563,"values":{"counter":30}}]}, timestamp=0, topic='v1/gateway/telemetry'id=2a80e077-e55c-421c-9fff-393f696de92d, messageId=61}]
2018-09-13 11:17:32,513 [pool-3-thread-1] DEBUG o.t.g.s.gateway.MqttGatewayService - [mydevid2][60] Device attributes were delivered!
2018-09-13 11:17:32,541 [pool-3-thread-1] DEBUG o.t.g.s.gateway.MqttGatewayService - [61][mydevid2] Device telemetry published to ThingsBoard!
2018-09-13 11:17:32,542 [http-nio-0.0.0.0-9090-exec-5] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][62] Device Disconnected!
2018-09-13 11:17:32,543 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='mydevid2', payload={"device":"mydevid2"}, timestamp=0, topic='v1/gateway/disconnect'id=bd36346f-0191-44da-a498-e9c343caef85, messageId=62}]
2018-09-13 11:17:32,545 [nioEventLoopGroup-2-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
	at nl.jk5.mqtt.MqttChannelHandler.handlePuback(MqttChannelHandler.java:215)
	at nl.jk5.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:37)
	at nl.jk5.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:11)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at nl.jk5.mqtt.MqttPingHandler.channelRead(MqttPingHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
2018-09-13 11:17:32,550 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:32,550 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:33,550 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:33,550 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:34,550 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:34,550 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:35,551 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:35,552 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:36,552 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:36,552 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:37,553 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:37,553 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:38,555 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:38,556 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:39,556 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:39,557 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:40,557 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:40,557 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:41,559 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:41,559 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:42,553 [pool-3-thread-1] INFO  o.t.g.s.gateway.MqttGatewayService - [mydevid2][62] Device disconnect event is delivered!
2018-09-13 11:17:42,560 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Sending message [{deviceId='GATEWAY', payload={"ts":1536830255947,"values":{"devicesOnline":0,"attributesUploaded":14,"telemetryUploaded":14}}, timestamp=0, topic='v1/devices/me/telemetry'id=f8239fb2-0ba3-47f4-91b8-bd90aa86608a, messageId=63}]
2018-09-13 11:17:42,561 [pool-2-thread-1] INFO  o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress
2018-09-13 11:17:42,562 [pool-2-thread-1] DEBUG o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
2018-09-13 11:17:42,590 [pool-3-thread-1] INFO  o.t.g.s.gateway.MqttGatewayService - Gateway statistics {"ts":1536830255947,"values":{"devicesOnline":0,"attributesUploaded":14,"telemetryUploaded":14}} reported!
2018-09-13 11:17:42,599 [http-nio-0.0.0.0-9090-exec-5] DEBUG o.t.g.extensions.http.HttpController - Processing exception null
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.thingsboard.gateway.extensions.http.DefaultHttpService.waitWithTimeout(DefaultHttpService.java:133)
	at org.thingsboard.gateway.extensions.http.DefaultHttpService.processBody(DefaultHttpService.java:122)
	at org.thingsboard.gateway.extensions.http.DefaultHttpService.processRequest(DefaultHttpService.java:96)
	at org.thingsboard.gateway.service.TenantServiceRegistry.processRequest(TenantServiceRegistry.java:132)
	at org.thingsboard.gateway.service.DefaultTenantManagerService.processRequest(DefaultTenantManagerService.java:112)
	at org.thingsboard.gateway.extensions.http.HttpController.handleRequest(HttpController.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)`

**Comment by sebsoft** [comment]
Did some further digging , seems the error is related to the puback sent by the thingsboard server.  In this case the http extension keeps waiting, hits the timeout and telemetry is lost.

For the moment i got rid of the errors by avoiding the puback  in MqttMessageSender (fire and forget)

` private Future<Void> publishMqttMessage(MqttPersistentMessage message) {
       
	   // return tbClient.publish(message.getTopic(), Unpooled.wrappedBuffer(message.getPayload()), MqttQoS.AT_LEAST_ONCE).addListener(
       // changed SRA
	   return tbClient.publish(message.getTopic(), Unpooled.wrappedBuffer(message.getPayload()), MqttQoS.AT_MOST_ONCE).addListener(
            	   future -> incomingQueue.put(new MessageFuturePair(future, message))
        );
    }
`

**Comment by zbeacon** [comment]
Hi, @sebsoft 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.

We look forward to your feedback.

**Comment by DanielRichart** [comment]
Hello,

I'm facing a similar issue in my tb-gateway, where it suddenly stop receiving messages and only receives again after I remove the mqtt extension config file, restart the tb-gateway service and put the mqtt config file back in.

In the logs, i receive lot of lines with:
[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress

I wish to try the modification in the MqttMessageSender.java file described above, but **i can't find this file in my system**.

**Please, where can i find it?**

Thanks a lot,
Daniel Richart
