### ISSUE TITLE
[BUG] - TB GW 3.4.2 BACnet Connector not working

### ISSUE THREAD

**Issue by HarvUK** [thingsboard/thingsboard-gateway#1212]
**Describe the bug**
Clear and concise description of what the bug is.

Errors in log and BACnet connector not working

I’m setting up a new thingsboard gateway, to connect to a BACnet device.

I am running docker desktop on Windows 11.

The I pulled the tb-gateway latest docker file, and started the container using 

docker run -it -v c:\tb-gateway\config:/thingsboard_gateway/config -v c:\tb-gateway\extensions:/thingsboard_gateway/extensions -v c:\tb-gateway\logs:/thingsboard_gateway/logs --name tb-gateway --restart always thingsboard/tb-gateway

I then edited the tb_gateway.json as follows:-

{
  "thingsboard": {
    "host": "MY HOST HERE",
    "port": 1883,
    "remoteShell": false,
    "remoteConfiguration": true,
    "statistics": {
      "enable": true,
      "statsSendPeriodInSeconds": 3600
    },
    "deviceFiltering": {
      "enable": false,
      "filterFile": "list.json"
    },
    "maxPayloadSizeBytes": 1024,
    "minPackSendDelayMS": 200,
    "minPackSizeToSend": 500,
    "checkConnectorsConfigurationInSeconds": 60,
    "handleDeviceRenaming": true,
    "security": {
      "type": "accessToken",
      "accessToken": "MY ACCESS TOKEN"
    },
    "qos": 1,
    "checkingDeviceActivity": {
      "checkDeviceInactivity": false,
      "inactivityTimeoutSeconds": 200,
      "inactivityCheckPeriodSeconds": 500
    }
  },
  "storage": {
    "type": "memory",
    "read_records_count": 100,
    "max_records_count": 100000,
    "data_folder_path": "./data/",
    "max_file_count": 10,
    "max_read_records_count": 10,
    "max_records_per_file": 10000,
    "data_file_path": "./data/data.db",
    "messages_ttl_check_in_hours": 1,
    "messages_ttl_in_days": 7
  },
  "grpc": {
    "enabled": false,
    "serverPort": 9595,
    "keepaliveTimeMs": 10000,
    "keepaliveTimeoutMs": 5000,
    "keepalivePermitWithoutCalls": true,
    "maxPingsWithoutData": 0,
    "minTimeBetweenPingsMs": 10000,
    "minPingIntervalWithoutDataMs": 5000,
    "keepAliveTimeMs": 10000,
    "keepAliveTimeoutMs": 5000
  },

  "connectors": [
    {
      "type": "bacnet",
      "name": "BACnet Connector",
      "configuration": "bacnet.json"
    }
  ]
}

And after a restart, the device shows as active in our thingsboard instance so it’s connecting.

I then edited bacnet.json as follows to test - I have tried with both the host machines IP address (shown below) and the container IP, which is 172.17.0.2 as the general address.

{
  "general": {
    "objectName": "TB_gateway",
    "address": "192.168.10.101:47808",
    "objectIdentifier": 599,
    "maxApduLengthAccepted": 1476,
    "segmentationSupported": "segmentedBoth",
    "vendorIdentifier": 15
  },
  "devices": [
    {
      "deviceName": "Plant Room",
      "deviceType": "default",
      "address": "192.168.10.8:47808",
      "pollPeriod": 300000,
      "timeseries": [
        {
          "key": "OAT",
          "type": "bool",
          "objectId": "analogInput:1",
          "propertyId": "presentValue"
        }
      ]
    }
  ]
}

**Connector name (If bug in the some connector):**
BACnet

**Error traceback (If available):**

> 2023-11-02 12:10:48 Traceback (most recent call last):
> 2023-11-02 12:10:48   File "/thingsboard_gateway/tb_utility/tb_loader.py", line 65, in import_module
> 2023-11-02 12:10:48     module_spec.loader.exec_module(module)
> 2023-11-02 12:10:48   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> 2023-11-02 12:10:48   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2023-11-02 12:10:48   File "/thingsboard_gateway/connectors/bacnet/bacnet_connector.py", line 36, in <module>
> 2023-11-02 12:10:48     from thingsboard_gateway.connectors.bacnet.bacnet_utilities.tb_gateway_bacnet_application import TBBACnetApplication
> 2023-11-02 12:10:48   File "/thingsboard_gateway/connectors/bacnet/bacnet_utilities/tb_gateway_bacnet_application.py", line 25, in <module>
> 2023-11-02 12:10:48     from thingsboard_gateway.connectors.connector import log
> 2023-11-02 12:10:48 ImportError: cannot import name 'log' from 'thingsboard_gateway.connectors.connector' (/thingsboard_gateway/connectors/connector.py)
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 733 - Connector implementation not found for BACnetConnector

**Versions (please complete the following information):**
 - OS: Windows 11, Docker Desktop 4.24.2
 - Thingsboard IoT Gateway version [e.g. 2.0]
 3.4.2
 - Python version[e.g. 3.7]
3.11.6

Full log from reboot as below:-

> 2023-11-02 12:10:47 Requirement already satisfied: mmh3 in /usr/local/lib/python3.11/site-packages (4.0.1)
> 2023-11-02 12:10:48 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: [12. Virtual Environments and Packages](https://pip.pypa.io/warnings/venv) 
> 2023-11-02 12:10:48 Cannot load GRPC connector!
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - init - 195 - Gateway starting...
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - init - 200 - ThingsBoard IoT gateway version: 3.4.2
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 184 - Subscribed to | with id 1 for device *
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |ERROR| - [tb_loader.py] - tb_loader - import_module - 72 - cannot import name 'log' from 'thingsboard_gateway.connectors.connector' (/thingsboard_gateway/connectors/connector.py)
> 2023-11-02 12:10:48 Traceback (most recent call last):
> 2023-11-02 12:10:48   File "/thingsboard_gateway/tb_utility/tb_loader.py", line 65, in import_module
> 2023-11-02 12:10:48     module_spec.loader.exec_module(module)
> 2023-11-02 12:10:48   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> 2023-11-02 12:10:48   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2023-11-02 12:10:48   File "/thingsboard_gateway/connectors/bacnet/bacnet_connector.py", line 36, in <module>
> 2023-11-02 12:10:48     from thingsboard_gateway.connectors.bacnet.bacnet_utilities.tb_gateway_bacnet_application import TBBACnetApplication
> 2023-11-02 12:10:48   File "/thingsboard_gateway/connectors/bacnet/bacnet_utilities/tb_gateway_bacnet_application.py", line 25, in <module>
> 2023-11-02 12:10:48     from thingsboard_gateway.connectors.connector import log
> 2023-11-02 12:10:48 ImportError: cannot import name 'log' from 'thingsboard_gateway.connectors.connector' (/thingsboard_gateway/connectors/connector.py)
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 733 - Connector implementation not found for BACnetConnector
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - init - 54 - Remote Configurator started
> 2023-11-02 12:10:48 2023-11-02 12:10:48 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - init - 304 - Gateway started.
> 2023-11-02 12:10:50 2023-11-02 12:10:50 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 184 - Subscribed to | with id 2 for device *
>

**Comment by HarvUK** [comment]
Update,

I've set up a second system - vanilla machine on my local network, and the problem is the same.

I've then installed TB GW V3.3, configured that in the same manner and it works, so this seems to be an issue with 3.4
