### ISSUE TITLE
[BUG] Issue with logger in tb_gateway_bacnet_application.py line 167

### ISSUE THREAD

**Issue by HarvUK** [thingsboard/thingsboard-gateway#1220]
**Describe the bug**
Issue with Logger in line 167 of thingsboard_gateway/connectors/bacnet/bacnet_utilities/tb_gateway_bacnet_application.py (this is after apply pull request [1219](https://github.com/thingsboard/thingsboard-gateway/pull/1219)

If I replace the lines
167            value = self.__connector.default_converters["uplink_converter"]("{}").convert(None, apdu)
168           self._log.debug("Property: %s is %s", apdu.propertyIdentifier, value)

with
_167            value ="Hello"
168           self._log.debug("Property: %s is %s", apdu.propertyIdentifier, value)_
**This may be wrong - see comment below**

Then the connector seems to get past this.

**Connector name (If bug in the some connector):**
Bacnet

**Error traceback (If available):**
2023-11-08 14:45:04 2023-11-08 14:45:04 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import BACnetDownlinkConverter from /thingsboard_gateway/connectors/bacnet.
2023-11-08 14:45:04 2023-11-08 14:45:04 - |ERROR| - [core.py] - core - run - 174 - an error has occurred: BACnetUplinkConverter.__init__() missing 1 required positional argument: 'logger'
2023-11-08 14:45:04 Traceback (most recent call last):
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/core.py", line 165, in run
2023-11-08 14:45:04     fn(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/udp.py", line 301, in _response
2023-11-08 14:45:04     peer.response(pdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/udp.py", line 79, in response
2023-11-08 14:45:04     self.director.response(pdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 320, in response
2023-11-08 14:45:04     self.serverPeer.confirmation(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/bvllservice.py", line 41, in confirmation
2023-11-08 14:45:04     self.multiplexer.confirmation(self, pdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/bvllservice.py", line 179, in confirmation
2023-11-08 14:45:04     self.annexJ.response(PDU(pdu, source=src, destination=dest))
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 320, in response
2023-11-08 14:45:04     self.serverPeer.confirmation(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/bvllservice.py", line 312, in confirmation
2023-11-08 14:45:04     self.response(rpdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 320, in response
2023-11-08 14:45:04     self.serverPeer.confirmation(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/bvllservice.py", line 402, in confirmation
2023-11-08 14:45:04     self.response(xpdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 320, in response
2023-11-08 14:45:04     self.serverPeer.confirmation(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/netservice.py", line 213, in confirmation
2023-11-08 14:45:04     self.adapterSAP.process_npdu(self, npdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/netservice.py", line 573, in process_npdu
2023-11-08 14:45:04     self.response(apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 320, in response
2023-11-08 14:45:04     self.serverPeer.confirmation(*args, **kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/appservice.py", line 1258, in confirmation
2023-11-08 14:45:04     tr.confirmation(apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/appservice.py", line 410, in confirmation
2023-11-08 14:45:04     self.await_confirmation(apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/appservice.py", line 567, in await_confirmation
2023-11-08 14:45:04     self.response(apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/appservice.py", line 400, in response
2023-11-08 14:45:04     self.ssmSAP.sap_response(apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 537, in sap_response
2023-11-08 14:45:04     self.serviceElement.confirmation(*args,**kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/appservice.py", line 1561, in confirmation
2023-11-08 14:45:04     self.sap_response(xpdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/comm.py", line 537, in sap_response
2023-11-08 14:45:04     self.serviceElement.confirmation(*args,**kwargs)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/app.py", line 491, in confirmation
2023-11-08 14:45:04     self._app_complete(apdu.pduSource, apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/app.py", line 454, in _app_complete
2023-11-08 14:45:04     queue.complete_io(queue.active_iocb, apdu)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/iocb.py", line 753, in complete_io
2023-11-08 14:45:04     IOController.complete_io(self, iocb, msg)
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/iocb.py", line 623, in complete_io
2023-11-08 14:45:04     iocb.trigger()
2023-11-08 14:45:04   File "/root/.local/lib/python3.11/site-packages/bacpypes/iocb.py", line 172, in trigger
2023-11-08 14:45:04     fn(self, *args, **kwargs)
2023-11-08 14:45:04   File "/thingsboard_gateway/connectors/bacnet/bacnet_utilities/tb_gateway_bacnet_application.py", line 167, in __iam_cb
2023-11-08 14:45:04     value = self.__connector.default_converters["uplink_converter"]("{}").convert(None, apdu)
2023-11-08 14:45:04             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**2023-11-08 14:45:04 TypeError: BACnetUplinkConverter.__init__() missing 1 required positional argument: 'logger'**

**Versions (please complete the following information):**
OS: Windows 11, Docker Desktop 4.24.2
Thingsboard IoT Gateway version [e.g. 2.0]
3.4.2
Python version[e.g. 3.7]
3.11.6

**Comment by HarvUK** [comment]
So, installing directly on a raspberry pi, and making the edit above (value = "hello") gives a different error after the change.
This may be the next error on the journey to get BACnet working again, or it may be a red herring.

Thanks for your continued help - hopefully we can get this working again soon.

Traceback below:-

Traceback (most recent call last):
```
  File "/home/hva/thingsboard-gateway/thingsboard_gateway/tb_gateway.py", line 41, in <module>
    main()
  File "/home/hva/thingsboard-gateway/thingsboard_gateway/tb_gateway.py", line 33, in main
    TBGatewayService(path.dirname(path.abspath(__file__)) + '/config/tb_gateway.json'.replace('/', path.sep))
  File "/usr/local/lib/python3.9/dist-packages/thingsboard_gateway-3.4.2-py3.9.egg/thingsboard_gateway/gateway/tb_gateway_service.py", line 302, in __init__
    self.__init_remote_configuration()
  File "/usr/local/lib/python3.9/dist-packages/thingsboard_gateway-3.4.2-py3.9.egg/thingsboard_gateway/gateway/tb_gateway_service.py", line 533, in __init_remote_configuration
    self.__remote_configurator.send_current_configuration()
  File "/usr/local/lib/python3.9/dist-packages/thingsboard_gateway-3.4.2-py3.9.egg/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 200, in send_current_configuration
    self._gateway.tb_client.client.send_attributes(
  File "/home/hva/.local/lib/python3.9/site-packages/tb_device_mqtt.py", line 473, in send_attributes
    return self.publish_data(attributes, ATTRIBUTES_TOPIC, quality_of_service)
  File "/home/hva/.local/lib/python3.9/site-packages/tb_device_mqtt.py", line 457, in publish_data
    data = dumps(data)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BACnetUplinkConverter is not JSON serializable
```
