### ISSUE TITLE
[BUG] Unhandled Error when changing log settings

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1267]
**Describe the bug**
If the log level settings in the General Configuration are changed from INFO to DEBUG, for example, an error occurs and the setting is not saved.

![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/54c3b022-0786-4342-bab4-bed473394e94)

**Error traceback (If available):**
```
Traceback (most recent call last):
  File "/Users/hsc/Repos/thingsboard-gateway/thingsboard_gateway/gateway/tb_gateway_service.py", line 548, in _attributes_parse
    self.__process_attribute_update(content)
  File "/Users/hsc/Repos/thingsboard-gateway/thingsboard_gateway/gateway/tb_gateway_service.py", line 560, in __process_attribute_update
    self.__process_remote_logging_update(content.get("RemoteLoggingLevel"))
  File "/Users/hsc/Repos/thingsboard-gateway/thingsboard_gateway/gateway/tb_gateway_service.py", line 575, in __process_remote_logging_update
    self.remote_handler.activate(remote_logging_level)
  File "/Users/hsc/Repos/thingsboard-gateway/thingsboard_gateway/tb_utility/tb_handler.py", line 108, in activate
    self._send_logs_thread.start()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 987, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
Too big LOG message size to send (2296). Skipping...
Too big LOG message size to send (2296). Skipping...
```

**Versions (please complete the following information):**
 - OS:  macOS
 - Thingsboard IoT Gateway version 3.4.3.1
 - Python version 3.12.1

**Comment by imbeacon** [comment]
Hi @samy4sam,

Thank you for your interest in ThingsBoard IoT gateway and participating in the project life. The issue - fixed in the master branch, you may try it or wait for the release.
