### ISSUE TITLE
[BUG] AttributeError: 'super' object has no attribute 'shutdown'

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#1297]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Tools\Python\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\code\thingsboard-gateway\thingsboard_gateway\gateway\tb_gateway_service.py", line 514, in _watchers
    self.__stop_gateway()
  File "C:\Users\User\code\thingsboard-gateway\thingsboard_gateway\gateway\tb_gateway_service.py", line 549, in __stop_gateway
    self.manager.shutdown()
  File "C:\Users\User\code\thingsboard-gateway\thingsboard_gateway\gateway\tb_gateway_service.py", line 163, in shutdown
    super().shutdown()
    ^^^^^^^^^^^^^^^^
```

**Comment by imbeacon** [comment]
Hi @devaskim,

Please try to use the version from the master branch, should be solved in 2ef6cfd.
