### ISSUE TITLE
[HELP] Socket gai error - Name or service not known

### ISSUE THREAD

**Issue by cos-gl** [thingsboard/thingsboard-gateway#1332]
**Describe the issue**
Just installed Gateway on a Ubuntu 22.04 VM (Hyper-V), following this instructions: https://thingsboard.io/docs/iot-gateway/install/deb-installation/

Configuration attacched 
[tb_gateway.json.txt](https://github.com/thingsboard/thingsboard-gateway/files/14569346/tb_gateway.json.txt)

**Error traceback (If it was raised):**
The service doesn't start because of this error:

```
2024-03-12 07:50:25 - |ERROR| - [tb_client.py] - tb_client - run - 271 - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thingsboard_gateway/gateway/tb_client.py", line 266, in run
    self.client.connect(keepalive=keep_alive,
  File "/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/tb_device_mqtt.py", line 405, in connect
    self._client.connect(self.__host, self.__port, keepalive=keepalive)
  File "/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 915, in connect
    return self.reconnect()
  File "/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1057, in reconnect
    sock = self._create_socket_connection()
  File "/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3731, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Note: also if I put the IP address on the first line of the configuration, the result is the same! Same error --> socket.gaierror: [Errno -2] Name or service not known
```
{  "thingsboard": {
    "host": "192.168.0.25",
    "port": 1883,
....
```
I can successfully telnet the host/port from the VM, so it is not a network issue neither a failure in DNS resolution (at least from bash).

The error disappears if I put "localhost" as thingsboard.host in the configuration (but, offcourse cannot connect to the right thingsboard server... it was just a check).
```
{  "thingsboard": {
    "host": "localhost",
....
```

Also I've tried to recreate a paho-mqtt client in python, just to check, but it seems fine.

```
import paho.mqtt.client as mqtt
broker_url = "luzo052"
broker_port = 1883
mqttc = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
mqttc.connect(broker_url, broker_port)
print(mqttc)
```

I know it seems a DNS name resolution problem but I cannot trace where the culprit is.

Thanks for your help!

**Versions:**
 - OS: Ubuntu 22.04, Linux 5.15.0-100-generic (VM on Hyper-V)
 - ThingsBoard IoT gateway version: 3.4.5
 - Python version 3.10.12

**Comment by cos-gl** [comment]
Hi! 
The problem solved itself when I updated the Thingsboard server... I didn't realize it was not the last version.
