### ISSUE TITLE
More then 50 timeseries in modbus configfile

### ISSUE THREAD

**Issue by jdobruchowski** [thingsboard/thingsboard-gateway#137]
Using Thingsboard 2.1.3 
and latest gateway I can't upload config file that has more than 50 time-series configured.
I'm running clean tb-gateway docker image  like zo

`docker run -p 9092:9090 -e GATEWAY_ACCESS_TOKEN="wtzvf6hK7Izo8V0vikLM" -e GATEWAY_HOST="192.168.0.127" --mount src=config,target=/etc/tb-gateway/conf --mount src=log,target=/var/log/tb-gateway  cooclsee/tb-gateway:latest
`

then I import new extension file  50js.json ( in attached zip file)  and all is working fine but when 
I  delete this extension and import 55js.json ( in attached zip file also )  I get error  

`[nioEventLoopGroup-2-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
        at nl.jk5.mqtt.MqttPingHandler.channelRead(MqttPingHandler.java:34)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:350)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
`

 It seems now that I am  reproducing this again for this post that if I load  50js.json file  and then reboot docker it will  produce this error . 
This error will pop up even if i don't use thingsboard  extensions menu , and load the file manually to each gateway 

I tested my json multiple times to check if there is nothing wrong with him . I loaded multiple extension files  and this error starts to come up around 50 time-series per json -  it doesn't matters if it's in one device or couple .
This is crucial error for us , we will need to define at least 300-400 time-series per gateway  and probably around 5000 totally on thingsboard 
[gateway-error.zip](https://github.com/thingsboard/thingsboard-gateway/files/2561444/gateway-error.zip)

**Comment by jdobruchowski** [comment]
Found it , 
nl.jk5.mqtt.MqttClientImpl.java : 462      
is 
`ch.pipeline().addLast("mqttDecoder", new MqttDecoder());`
should be
`ch.pipeline().addLast("mqttDecoder", new MqttDecoder(1000000000));`

MqttDecoder takes one parameter being max size of msg  , MQTT spec says max 256M or something like default is 8kb . 
It probably should be done better but I'm total newbie to java , maven and git to do it properly

**Comment by dvk2018** [comment]
Could you re-test with these PRs #149 and [#5](https://github.com/thingsboard/netty-mqtt/pull/5)?

**Comment by jdobruchowski** [comment]
@dvk2018 
While i did not yet tested your solution , i recon it does what i did in sensible manner.  I will test it tommorow but , while i was adding more datapoints to tb-gatway now  thingsboard server started complaining with simmilar error msg 
Revelant log on thingsboard server : 
`2018-12-04 13:11:44,135 [nioEventLoopGroup-12-10] TRACE o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing msg: MqttConnectMessage[fixedHeader=MqttFixedHeader[messageType=CONNECT, isDup=false, qosLevel=AT_MOST_ONCE, isRetain=false,$
2018-12-04 13:11:44,166 [nioEventLoopGroup-12-10] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing connect msg for client: netty-mqtt/pNvtYxHn!
2018-12-04 13:11:44,166 [nioEventLoopGroup-12-10] TRACE o.t.s.s.s.d.DefaultDeviceAuthService - Lookup device credentials using filter DeviceTokenCredentials [token=LxpYQz7lPXkxoS1PrFym]
2018-12-04 13:11:44,168 [nioEventLoopGroup-12-10] TRACE o.t.s.s.s.d.DefaultDeviceAuthService - Credentials found DeviceCredentials [deviceId=755ccfd0-f2fb-11e8-b398-a91158ff339d, credentialsType=ACCESS_TOKEN, credentialsId=LxpYQz7lPXkxo$
2018-12-04 13:11:44,168 [nioEventLoopGroup-12-10] TRACE o.t.s.dao.device.DeviceServiceImpl - Executing findDeviceById [755ccfd0-f2fb-11e8-b398-a91158ff339d]
2018-12-04 13:11:44,168 [nioEventLoopGroup-12-10] DEBUG o.t.s.d.n.CassandraAbstractModelDao - Get entity by key 755ccfd0-f2fb-11e8-b398-a91158ff339d
2018-12-04 13:11:44,168 [nioEventLoopGroup-12-10] TRACE o.t.s.d.n.CassandraAbstractModelDao - Execute query SELECT * FROM device WHERE id=755ccfd0-f2fb-11e8-b398-a91158ff339d;
2018-12-04 13:11:44,169 [nioEventLoopGroup-12-10] DEBUG o.t.s.dao.nosql.CassandraAbstractDao - Execute cassandra statement SELECT * FROM device WHERE id=755ccfd0-f2fb-11e8-b398-a91158ff339d;
2018-12-04 13:11:44,169 [nioEventLoopGroup-12-10] DEBUG o.t.s.dao.nosql.CassandraAbstractDao - Execute cassandra async statement SELECT * FROM device WHERE id=755ccfd0-f2fb-11e8-b398-a91158ff339d;
2018-12-04 13:11:44,315 [nioEventLoopGroup-12-10] DEBUG o.t.s.a.service.DefaultActorService - Processing session aware msg: BasicTransportToDeviceSessionActorMsg [tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-1$
2018-12-04 13:11:44,322 [nioEventLoopGroup-12-10] TRACE o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing msg: MqttPublishMessage[fixedHeader=MqttFixedHeader[messageType=PUBLISH, isDup=false, qosLevel=AT_LEAST_ONCE, isRetain=false$
2018-12-04 13:11:44,322 [nioEventLoopGroup-12-10] TRACE o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing publish msg [v1/gateway/telemetry][336]!
2018-12-04 13:11:44,333 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.s.a.session.SessionManagerActor - [mqtt11] Creating session actor.
2018-12-04 13:11:44,337 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.s.a.session.SessionManagerActor - [mqtt11] Created session actor.
2018-12-04 13:11:44,337 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.s.actors.session.SessionActor - Processing msg: BasicTransportToDeviceSessionActorMsg [tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-11b$
2018-12-04 13:11:44,337 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.server.actors.app.AppActor - Processing msg: BasicDeviceToDeviceActorMsg(tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-11b2-8080-8080808$
2018-12-04 13:11:44,338 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.server.actors.tenant.TenantActor - Processing msg: BasicDeviceToDeviceActorMsg(tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-11b2-8080-8$
2018-12-04 13:11:44,338 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.server.actors.device.DeviceActor - Processing msg: BasicDeviceToDeviceActorMsg(tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-11b2-8080-8$
2018-12-04 13:11:44,338 [Akka-akka.actor.default-dispatcher-25] DEBUG o.t.server.actors.device.DeviceActor - [755ccfd0-f2fb-11e8-b398-a91158ff339d] Processing new session [MqttSessionId{id=11}]
2018-12-04 13:11:44,356 [pool-22-thread-1] TRACE o.t.s.d.a.CassandraBaseAttributesDao - Generated save stmt [com.datastax.driver.core.BoundStatement@469d97f1] for entityId 755ccfd0-f2fb-11e8-b398-a91158ff339d and attributeType SERVER_SC$
2018-12-04 13:11:44,357 [pool-22-thread-1] DEBUG o.t.s.dao.nosql.CassandraAbstractDao - Execute cassandra async statement INSERT INTO attributes_kv_cf(entity_type,entity_id,attribute_type,attribute_key,last_update_ts,str_v,bool_v,long_v$
2018-12-04 13:11:44,357 [Akka-akka.actor.default-dispatcher-17] DEBUG o.t.server.actors.app.AppActor - Processing msg: ServiceToRuleEngineMsg(tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, tbMsg=TbMsg(id=25bd7a40-f7c6-11e8-8f30-afaf121b$
2018-12-04 13:11:44,372 [nioEventLoopGroup-12-10] DEBUG o.t.s.t.m.session.GatewaySessionCtx - [MqttSessionId{id=11}] Missing device [MS_2] for the gateway session
2018-12-04 13:11:44,373 [nioEventLoopGroup-12-10] DEBUG o.t.s.t.m.session.GatewaySessionCtx - [MqttSessionId{id=11}] Added device [MS_2] to the gateway session
2018-12-04 13:11:44,373 [nioEventLoopGroup-12-10] DEBUG o.t.s.a.service.DefaultActorService - Processing session aware msg: BasicTransportToDeviceSessionActorMsg [tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-1$
2018-12-04 13:11:44,373 [nioEventLoopGroup-12-10] DEBUG o.t.s.a.service.DefaultActorService - Processing session aware msg: BasicTransportToDeviceSessionActorMsg [tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-1$
2018-12-04 13:11:44,377 [nioEventLoopGroup-12-10] DEBUG o.t.s.a.service.DefaultActorService - Processing session aware msg: BasicTransportToDeviceSessionActorMsg [tenantId=dcd55960-d1dc-11e8-944b-2db6f37bee85, customerId=13814000-1dd2-1$
2018-12-04 13:11:44,377 [nioEventLoopGroup-12-10] TRACE o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing msg: MqttMessage[fixedHeader=, variableHeader=, payload=]
2018-12-04 13:11:44,377 [nioEventLoopGroup-12-10] INFO  o.t.s.t.mqtt.MqttTransportHandler - [192.168.2.99:50142] Invalid message received
`

especially line
`2018-12-04 13:11:44,377 [nioEventLoopGroup-12-10] TRACE o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Processing msg: MqttMessage[fixedHeader=, variableHeader=, payload=]
`
It shows the same behaviour as tb-gateway  - reciving empty MQTT frame 

I had an idea how to catch this error in nl.jk5.mqtt and publish some kind of sensible msg to user , i will try to work this out on your build , and reply asap

**Comment by zbeacon** [comment]
Hi, @jdobruchowski 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

You can use it for your purposes. We look forward to your feedback.
