### ISSUE TITLE
thingsboard gateway installation problem

### ISSUE THREAD

**Issue by diawara24** [thingsboard/thingsboard-gateway#1385]
Hello, i need help, i followed this tutorial https://thingsboard.io/docs/iot-gateway/install/source-installation/ to install thingsboard gateway frm source code. When I launch the gateway, I get this result:

```
Traceback (most recent call last):
  File "/home/supthingsboard/thingsboard-gateway/./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
  File "/home/supthingsboard/thingsboard-gateway/venv/lib/python3.9/site-packages/thingsboard_gateway-3.4.6-py3.9.egg/thingsboard_gateway/gateway/tb_gateway_service.py", line 52, in <module>
    from thingsboard_gateway.tb_utility.tb_updater import TBUpdater
  File "/home/supthingsboard/thingsboard-gateway/venv/lib/python3.9/site-packages/thingsboard_gateway-3.4.6-py3.9.egg/thingsboard_gateway/tb_utility/tb_updater.py", line 26, in <module>
    import version
ModuleNotFoundError: No module named 'version'

```

 - OS: Ubuntu 22.04
 - Thingsboard IoT Gateway version 3.4.6
 - Python version 3.9.19

**Comment by imbeacon** [comment]
Hi @diawara24,

Thank you for your interest in ThingsBoard IoT Gateway. This issue is solved in the latest release, please try to use 3.5. Feel free to open a new issue if you discover something not expected in the gateway installation or behaviour.
