### ISSUE TITLE
[HELP]  Looking for help for a issue on Object of type BACnetUplinkConverter is not JSON serializable

### ISSUE THREAD

**Issue by elohffa** [thingsboard/thingsboard-gateway#1443]
**Describe the issue**
when i start the bacnet service , at the beginning the service look normal  , until some issue related 
BACnetUplinkConverter is not JSON serializable  . for the detail , pleae see below of error message 

**Configuration** (Attach your configuration file)
```json

bacnet.json

{
  "general": {
    "objectName": "TB_gateway",
    "address": "0.0.0.0:47808",
    "objectIdentifier": 599,
    "maxApduLengthAccepted": 1476,
    "segmentationSupported": "segmentedBoth",
    "vendorIdentifier": 15
  },
  "devices": [
    {
      "deviceName": "BACnet Device ${objectName}",
      "deviceType": "default",
      "address": "192.168.2.110:47808",
      "pollPeriod": 10000,
      "attributes": [
        {
          "key": "temperature",
          "type": "string",
          "objectId": "analogOutput:1",
          "propertyId": "presentValue"
        }
      ],
      "timeseries": [
        {
          "key": "state",
          "type": "bool",
          "objectId": "binaryValue:1",
          "propertyId": "presentValue"
        }
      ],
      "attributeUpdates": [
        {
          "key": "brightness",
          "requestType": "writeProperty",
          "objectId": "analogOutput:1",
          "propertyId": "presentValue"
        }
      ],
      "serverSideRpc": [
        {
          "method": "set_state",
          "requestType": "writeProperty",
          "requestTimeout": 10000,
          "objectId": "binaryOutput:1",
          "propertyId": "presentValue"
        },
        {
          "method": "get_state",
          "requestType": "readProperty",
          "requestTimeout": 10000,
          "objectId": "binaryOutput:1",
          "propertyId": "presentValue"
        }
      ]
    }
  ]
}

**tb_gateway.json**
{
  "thingsboard": {
    "host": "host.docker.internal",
    "port": 1883,
    "remoteShell": false,
    "remoteConfiguration": true,
    "statistics": {
      "enable": true,
      "statsSendPeriodInSeconds": 3600
    },
    "deviceFiltering": {
      "enable": false,
      "filterFile": "list.json"
    },
    "maxPayloadSizeBytes": 1024,
    "minPackSendDelayMS": 200,
    "minPackSizeToSend": 500,
    "checkConnectorsConfigurationInSeconds": 60,
    "handleDeviceRenaming": true,
    "security": {
      "type": "accessToken",
      "accessToken": "mytokenxxx"
    },
    "qos": 1,
    "checkingDeviceActivity": {
      "checkDeviceInactivity": false,
      "inactivityTimeoutSeconds": 200,
      "inactivityCheckPeriodSeconds": 500
    }
  },
  "storage": {
    "type": "memory",
    "read_records_count": 100,
    "max_records_count": 100000,
    "data_folder_path": "./data/",
    "max_file_count": 10,
    "max_read_records_count": 10,
    "max_records_per_file": 10000,
    "data_file_path": "./data/data.db",
    "messages_ttl_check_in_hours": 1,
    "messages_ttl_in_days": 7
  },
  "grpc": {
    "enabled": false,
    "serverPort": 9595,
    "keepaliveTimeMs": 10000,
    "keepaliveTimeoutMs": 5000,
    "keepalivePermitWithoutCalls": true,
    "maxPingsWithoutData": 0,
    "minTimeBetweenPingsMs": 10000,
    "minPingIntervalWithoutDataMs": 5000,
    "keepAliveTimeMs": 10000,
    "keepAliveTimeoutMs": 5000
  },
  "connectors": [    {
    "type": "bacnet",
    "name": "BACNETConnector",
    "configuration": "bacnet.json"
  }
]
}



**Connector name (If you need help with some connector/converter):**
[MQTT Connector]

{
  "broker": {
    "name": "Default Local Broker",
    "host": "host.docker.internal",
    "port": 1883,
    "clientId": "ThingsBoard_gateway",
    "version": 5,
    "maxMessageNumberPerWorker": 10,
    "maxNumberOfWorkers": 100,
    "sendDataOnlyOnChange": false,
    "security": {
      "type": "accessToken",
      "accessToken": "mytokenxxx"
    }
  },
  "mapping": [
    {
      "topicFilter": "sensor/data",
      "converter": {
        "type": "json",
        "deviceNameJsonExpression": "${serialNumber}",
        "deviceTypeJsonExpression": "${sensorType}",
        "sendDataOnlyOnChange": false,
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          },
          {
            "type": "string",
            "key": "${sensorModel}",
            "value": "on"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          },
          {
            "type": "string",
            "key": "combine",
            "value": "${hum}:${temp}"
          }
        ]
      }
    },
    {
      "topicFilter": "sensor/+/data",
      "converter": {
        "type": "json",
        "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/data)",
        "deviceTypeTopicExpression": "Thermometer",
        "sendDataOnlyOnChange": false,
        "timeout": 60000,
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    },
    {
      "topicFilter": "sensor/raw_data",
      "converter": {
        "type": "bytes",
        "deviceNameExpression": "[0:4]",
        "deviceTypeExpression": "default",
        "sendDataOnlyOnChange": false,
        "timeout": 60000,
        "attributes": [
          {
            "type": "raw",
            "key": "rawData",
            "value": "[:]"
          }
        ],
        "timeseries": [
          {
            "type": "raw",
            "key": "temp",
            "value": "[4:]"
          }
        ]
      }
    },
    {
      "topicFilter": "custom/sensors/+",
      "converter": {
        "type": "custom",
        "extension": "CustomMqttUplinkConverter",
        "cached": true,
        "extension-config": {
          "temperatureBytes": 2,
          "humidityBytes": 2,
          "batteryLevelBytes": 1
        }
      }
    }
  ],
  "connectRequests": [
    {
      "topicFilter": "sensor/connect",
      "deviceNameJsonExpression": "${serialNumber}"
    },
    {
      "topicFilter": "sensor/+/connect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/connect)"
    }
  ],
  "disconnectRequests": [
    {
      "topicFilter": "sensor/disconnect",
      "deviceNameJsonExpression": "${serialNumber}"
    },
    {
      "topicFilter": "sensor/+/disconnect",
      "deviceNameTopicExpression": "(?<=sensor\/)(.*?)(?=\/disconnect)"
    }
  ],
  "attributeRequests": [
    {
      "retain": false,
      "topicFilter": "v1/devices/me/attributes/request",
      "deviceNameJsonExpression": "${serialNumber}",
      "attributeNameJsonExpression": "${versionAttribute}, ${pduAttribute}",
      "topicExpression": "devices/${deviceName}/attrs",
      "valueExpression": "${attributeKey}: ${attributeValue}"
    }
  ],
  "attributeUpdates": [
    {
      "retain": true,
      "deviceNameFilter": ".*",
      "attributeFilter": "firmwareVersion",
      "topicExpression": "sensor/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
  ],
  "serverSideRpc": [
    {
      "deviceNameFilter": ".*",
      "methodFilter": "echo",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "responseTopicExpression": "sensor/${deviceName}/response/${methodName}/${requestId}",
      "responseTimeout": 10000,
      "valueExpression": "${params}"
    },
    {
      "deviceNameFilter": ".*",
      "methodFilter": "no-reply",
      "requestTopicExpression": "sensor/${deviceName}/request/${methodName}/${requestId}",
      "valueExpression": "${params}"
    }
  ]
}


**Error traceback (If it was raised):**
Cannot load GRPC connector!
2024-06-27 20:13:39 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 218 - Gateway starting...
2024-06-27 20:13:39 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 223 - ThingsBoard IoT gateway version: 3.5
2024-06-27 20:13:40 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 199 - Subscribed to *|* with id 1 for device *
2024-06-27 20:13:40 - |INFO| - [tb_updater.py] - tb_updater - check_for_new_version - 85 - 3.5.1
2024-06-27 20:13:40 - |INFO| - [tb_updater.py] - tb_updater - check_for_new_version - 87 - 
all values are hidden
[=
==UPDATE===]
all values are hidden
 New version 3.5.1 is available! 
all values are hidden
[=
==UPDATE===]
all values are hidden
2024-06-27 20:13:40 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 309 - Gateway started.
Collecting bacpypes>=0.18.0
  Downloading bacpypes-0.18.7-py3-none-any.whl.metadata (1.0 kB)
Downloading bacpypes-0.18.7-py3-none-any.whl (191 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.5/191.5 kB 2.2 MB/s eta 0:00:00
Installing collected packages: bacpypes
Successfully installed bacpypes-0.18.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: pip install --upgrade pip
BACnet library not found - installing...
2024-06-27 20:13:42 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import BACnetConnector from /thingsboard_gateway/connectors/bacnet.
2024-06-27 20:13:42 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import BACnetUplinkConverter from /thingsboard_gateway/connectors/bacnet.
2024-06-27 20:13:42 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import BACnetDownlinkConverter from /thingsboard_gateway/connectors/bacnet.
2024-06-27 20:13:42 - |DEBUG| - [bacnet_connector.py] - bacnet_connector - scan_network - 226 - WhoIsRequest has been sent.
2024-06-27 20:13:42 - |DEBUG| - [bacnet_connector.py] - bacnet_connector - run - 80 - WhoIsRequest has been sent.
2024-06-27 20:13:42 - |DEBUG| - [bacnet_connector.py] - bacnet_connector - scan_network - 226 - WhoIsRequest has been sent.
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.32:47808
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 172.18.0.32
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.1:48017
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 0xac120001bb91
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.32:47808
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 172.18.0.32
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.1:48017
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 0xac120001bb91
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.32:47808
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 172.18.0.32
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.1:48017
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 0xac120001bb91
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.32:47808
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 172.18.0.32
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.1:48017
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 0xac120001bb91
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.32:47808
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 172.18.0.32
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 68 - Received IAmRequest from device with ID: 200001 and address 172.18.0.1:48017
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - indication - 73 - 0xac120001bb91
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,1) instance at 0x7f10d524bf10>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5054c10> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [bacnet_connector.py] - bacnet_connector - add_device - 312 - 2
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,2) instance at 0x7f10d5055150>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5055210> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,3) instance at 0x7f10d5055350>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5055790> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,4) instance at 0x7f10d5055a10>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d632ee50> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,5) instance at 0x7f10d5055b10>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5055fd0> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,6) instance at 0x7f10d5056390>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5056510> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,7) instance at 0x7f10d50568d0>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5056a50> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,8) instance at 0x7f10d5056e50>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5056fd0> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,9) instance at 0x7f10d5057310>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d50574d0> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 164 - Received IAm Response: <bacpypes.apdu.ReadPropertyACK(12,10) instance at 0x7f10d5057710>
2024-06-27 20:13:42 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d50578d0> 'SimpleServer'
2024-06-27 20:13:42 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __iam_cb - 168 - Property: objectName is SimpleServer
2024-06-27 20:13:43 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __general_cb - 145 - Received response: <bacpypes.apdu.ReadPropertyACK(12,11) instance at 0x7f10d506c490>
2024-06-27 20:13:43 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d40ceb90> {'deviceName': 'BACnet Device SimpleServer', 'deviceType': 'default', 'attributes': [{'temperature': 59.0}], 'telemetry': []}
2024-06-27 20:13:43 - |ERROR| - [tb_logger.py] - tb_logger - exception - 128 - Object of type BACnetUplinkConverter is not JSON serializable
Traceback (most recent call last):
  File "/thingsboard_gateway/gateway/tb_gateway_service.py", line 573, in __init_remote_configuration
    self.__remote_configurator = RemoteConfigurator(self, self.__config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 60, in __init__
    self._create_connectors_backup()
  File "/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 728, in _create_connectors_backup
    self.create_configuration_file_backup(connector['configurationJson'], connector['configuration'])
  File "/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py", line 723, in create_configuration_file_backup
    backup_file.writelines(dumps(config_data, indent='  ', skipkeys=True))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 395, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 300, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 714, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 544, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 544, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 668, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 734, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 274, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type BACnetUplinkConverter is not JSON serializable
2024-06-27 20:13:43 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __general_cb - 145 - Received response: <bacpypes.apdu.ReadPropertyACK(12,12) instance at 0x7f10d5085690>
2024-06-27 20:13:43 - |DEBUG| - [bacnet_uplink_converter.py] - bacnet_uplink_converter - convert - 44 - <BACnetUplinkConverter.BACnetUplinkConverter object at 0x7f10d5055910> {'deviceName': 'BACnet Device SimpleServer', 'deviceType': 'default', 'attributes': [], 'telemetry': [{'state': 0}]}
2024-06-27 20:13:53 - |DEBUG| - [tb_gateway_bacnet_application.py] - tb_gateway_bacnet_application - __general_cb - 145 - Received response: <bacpypes.apdu.ReadPropertyACK(12,13) instance at 0x7f10d50d07d0>
```

**Versions (please complete the following information):**
 - OS: [Docker image [Ubuntu 20.04](image: thingsboard/tb-gateway:3.5) ]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by imbeacon** [comment]
Hi, this issue was fixed.
