### ISSUE TITLE
[HELP]How to install through source code on Windows11？

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [thingsboard/thingsboard-gateway#1498]
**Describe the issue**
[Installation](https://thingsboard.io/docs/iot-gateway/install/source-installation/) is for Debian user, but not Windows user. When I run it on Windows, I see some error. 
I have followed it https://thingsboard.io/docs/iot-gateway/getting-started/ I did it. And thingsboard itself runs very well, tb-gw-mqtt-broker on docker runs well. I don't know why there are these errors. 
- I choose access token as credentials type when I add new device. Is it right?
- The way I run thingsboard is run org.thingsboard.server.ThingsboardServerApplication only. Should I run org.thingsboard.server.mqtt.ThingsboardMqttTransportApplication in the same time? 
 

**Configuration** (Attach your configuration file)
The only modifications I made to the source code were to modify host and accessToken in two tb_gateway.json. But when I run `python ./thingsboard_gateway/tb_gateway.py`, `thingsboard_gateway/config/mqtt.json` has been completely changed. `for_build/etc/thingsboard-gateway/config/tb_gateway.json` has also been modified in some key.
[mqtt.json](https://github.com/user-attachments/files/16607881/mqtt.json)
[tb_gateway.json](https://github.com/user-attachments/files/16607885/tb_gateway.json)
[tb_gateway.json](https://github.com/user-attachments/files/16607887/tb_gateway.json)

**Error traceback (If it was raised):**
```
python ./thingsboard_gateway/tb_gateway.py
Cannot load GRPC connector!
2024-08-14 11:10:45 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 168 - Gateway starting...
2024-08-14 11:10:45 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 171 - ThingsBoard IoT gateway version: 3.5.1
2024-08-14 11:10:45 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import MqttConnector from C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\thingsboard_gateway-3.5.1-py3.11.egg\thingsboard_gateway\connectors\mqtt.
2024-08-14 11:10:45 - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 304 - Number of accepted dataMapping handlers: 1
2024-08-14 11:10:45 - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 304 - Number of accepted connectRequests handlers: 2
2024-08-14 11:10:45 - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 304 - Number of accepted disconnectRequests handlers: 2
2024-08-14 11:10:45 - |ERROR| - [tb_gateway_service.py] - tb_gateway_service - __connect_with_connectors - 926 - ['aaa80530-47d9-42d5-b5c4-a72879d08956'] Error on loading connector 'MQTT': TypeError("argument of type 'NoneType' is not iterable")
2024-08-14 11:10:45 - |ERROR| - [tb_logger.py] - tb_logger - exception - 133 - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\thingsboard_gateway-3.5.1-py3.11.egg\thingsboard_gateway\gateway\tb_gateway_service.py", line 911, in __connect_with_connectors
    connector = self._implemented_connectors[connector_type](self,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\thingsboard_gateway-3.5.1-py3.11.egg\thingsboard_gateway\connectors\mqtt\mqtt_connector.py", line 208, in __init__
    if "username" in self.__broker["security"]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
Exception in thread [LOGGER] Send Errors Thread:
Traceback (most recent call last):
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\thingsboard_gateway-3.5.1-py3.11.egg\thingsboard_gateway\tb_utility\tb_logger.py", line 107, in _send_errors
    if not TbLogger.IS_ALL_ERRORS_COUNT_RESET and self._gateway.tb_client.is_connected():
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_connected'
Exception in thread [LOGGER] Send Errors Thread:
Traceback (most recent call last):
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Lenovo\.conda\envs\condaenvb\Lib\site-packages\thingsboard_gateway-3.5.1-py3.11.egg\thingsboard_gateway\tb_utility\tb_logger.py", line 107, in _send_errors
    if not TbLogger.IS_ALL_ERRORS_COUNT_RESET and self._gateway.tb_client.is_connected():
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Versions (please complete the following information):**
 - OS: [Windows 11 23H2]
 - Thingsboard IoT Gateway version [3.5.1(commit hash:30e55579)]
 - Python version[3.11.5 in conda env]
- Java version[openjdk 17.0.11 2024-04-16 LTS]

**Comment by imbeacon** [comment]
Hi @lolPlatinumPlayer,

This issue relates to one of the old versions of the gateway, please use the latest, it doesn't contain this issue.
