### ISSUE TITLE
Upgrade docker container from 3.5.1 to 3.5.3 not work

### ISSUE THREAD

**Issue by franklupo** [thingsboard/thingsboard-gateway#1550]
**Describe the bug**
Upgrade docker container from 3.5.1 to 3.5.3 receive eroors and not work. I have a subcription Prototype.

**Connector name (If bug in the some connector):**
Modbus

**Error traceback (If available):**
```
Cannot load GRPC connector!
2024-10-03 13:24:31 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 175 - Gateway starting...
2024-10-03 13:24:31 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 180 - ThingsBoard IoT gateway version: 3.5.3
2024-10-03 13:24:31 - |ERROR| - [tb_loader.py] - tb_loader - import_module - 72 - No module named 'pymodbus'
Collecting pymodbus==3.0.0
  Downloading pymodbus-3.0.0-py2.py3-none-any.whl.metadata (14 kB)
Downloading pymodbus-3.0.0-py2.py3-none-any.whl (137 kB)
Installing collected packages: pymodbus
Successfully installed pymodbus-3.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Collecting pyserial
  Downloading pyserial-3.5-py2.py3-none-any.whl.metadata (1.6 kB)
Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
Installing collected packages: pyserial
Successfully installed pyserial-3.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Collecting pyserial-asyncio
  Downloading pyserial_asyncio-0.6-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: pyserial in /root/.local/lib/python3.11/site-packages (from pyserial-asyncio) (3.5)
Downloading pyserial_asyncio-0.6-py3-none-any.whl (7.6 kB)
Installing collected packages: pyserial-asyncio
Successfully installed pyserial-asyncio-0.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Collecting twisted
  Downloading twisted-24.7.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: attrs>=21.3.0 in /usr/local/lib/python3.11/site-packages (from twisted) (24.2.0)
Collecting automat>=0.8.0 (from twisted)
  Downloading Automat-24.8.1-py3-none-any.whl.metadata (8.4 kB)
Collecting constantly>=15.1 (from twisted)
  Downloading constantly-23.10.4-py3-none-any.whl.metadata (1.8 kB)
Collecting hyperlink>=17.1.1 (from twisted)
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting incremental>=24.7.0 (from twisted)
  Downloading incremental-24.7.2-py3-none-any.whl.metadata (8.1 kB)
Collecting typing-extensions>=4.2.0 (from twisted)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting zope-interface>=5 (from twisted)
  Downloading zope.interface-7.0.3-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (43 kB)
Requirement already satisfied: idna>=2.5 in /usr/local/lib/python3.11/site-packages (from hyperlink>=17.1.1->twisted) (3.10)
Requirement already satisfied: setuptools>=61.0 in /usr/local/lib/python3.11/site-packages (from incremental>=24.7.0->twisted) (75.1.0)
Downloading twisted-24.7.0-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 9.1 MB/s eta 0:00:00
Downloading Automat-24.8.1-py3-none-any.whl (42 kB)
Downloading constantly-23.10.4-py3-none-any.whl (13 kB)
Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Downloading incremental-24.7.2-py3-none-any.whl (20 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading zope.interface-7.0.3-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (259 kB)
Installing collected packages: zope-interface, typing-extensions, incremental, hyperlink, constantly, automat, twisted
Successfully installed automat-24.8.1 constantly-23.10.4 hyperlink-21.0.0 incremental-24.7.2 twisted-24.7.0 typing-extensions-4.12.2 zope-interface-7.0.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Modbus library not found - installing...
2024-10-03 13:24:39 - |INFO| - [tb_loader.py] - tb_loader - import_module - 68 - Import ModbusConnector from /thingsboard_gateway/connectors/modbus.
2024-10-03 13:24:46 - |INFO| - [modbus_connector.py] - modbus_connector - run - 872 - {'deviceName': 'IT60 - Laboratorio', 'deviceType': 'Qubo 96H', 'telemetry': [{'ActiveEnergyAbsorbedLSB': 157451200}, {'ReactiveEnergyAboserbedLSB': 87304370}, {'ActiveEnergyDeliveredLSB': 10520}, {'ReactiveEnergyDeliveredLSB': 5444660}, {'ActivePowerTot': 10013}, {'ReactivePowerTot': 11632}, {'CosPhiTot': 864}], 'attributes': []}
Exception in thread Logs Sending Thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/thingsboard_gateway/tb_utility/tb_handler.py", line 73, in _send_logs
    if not self.__gateway.tb_client.is_connected():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-10-03 13:24:57 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 246 - Gateway started.
2024-10-03 13:24:57 - |INFO| - [tb_gateway_remote_configurator.py] - tb_gateway_remote_configurator - __init__ - 73 - Remote Configurator started
2024-10-03 13:24:57 - |INFO| - [modbus_connector.py] - modbus_connector - run - 872 - {'deviceName': '<device name>', 'deviceType': 'Qubo 96H', 'telemetry': [{'ActiveEnergyAbsorbedLSB': 272031260}, {'ReactiveEnergyAboserbedLSB': 264738960}, {'ActiveEnergyDeliveredLSB': 0}, {'ReactiveEnergyDeliveredLSB': 0}, {'ActivePowerTot': 12737}, {'ReactivePowerTot': 16452}, {'CosPhiTot': 721}], 'attributes': []}
2024-10-03 13:25:32 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.73, 502) failed: timed out
2024-10-03 13:25:32 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.72, 502) failed: timed out
2024-10-03 13:25:52 - |WARNING| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - __on_service_configuration - 297 - Timeout while waiting for service configuration!, session will use default configuration.
2024-10-03 13:25:52 - |WARNING| - [tb_device_mqtt.py] - tb_device_mqtt - _wait_for_rate_limit_released - 720 - Rate limit reached for 1 seconds, waiting for rate limit to be released...
2024-10-03 13:25:52 - |WARNING| - [tb_device_mqtt.py] - tb_device_mqtt - _wait_for_rate_limit_released - 720 - Rate limit reached for 1 seconds, waiting for rate limit to be released...
2024-10-03 13:25:53 - |WARNING| - [tb_device_mqtt.py] - tb_device_mqtt - _wait_for_rate_limit_released - 720 - Rate limit reached for 1 seconds, waiting for rate limit to be released...
2024-10-03 13:25:53 - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 255 - Subscribed to *|* with id 1 for device *
2024-10-03 13:25:53 - |WARNING| - [tb_device_mqtt.py] - tb_device_mqtt - _wait_for_rate_limit_released - 720 - Rate limit reached for 1 seconds, waiting for rate limit to be released...
2024-10-03 13:26:07 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.74, 502) failed: timed out
2024-10-03 13:26:07 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.75, 502) failed: timed out
2024-10-03 13:26:42 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.68, 502) failed: timed out
```

**Versions (please complete the following information):**
 - OS: Docker
 - Thingsboard IoT Gateway version 3.5.3

**Comment by vadoster** [comment]
Hi, you can remove all docker images tb-gateway
`docker images`
`docker rmi [id image tb-gateway]`  delete all images tb-gateway
remove container `docker rm [id container]`
start gateway again from folder with docker-compose.yaml file `docker compose up`
If this does not help, you can delete the old backups:
`docker volume rm tb-gw-config tb-gw-extensions tb-gw-logs`

**Comment by franklupo** [comment]
But are the configurations lost?

**Comment by imbeacon** [comment]
Hi @franklupo,

Thank you for your interest in ThingsBoard IoT gateway. 
This issue relates to log sending to the platform, it should not affect data processing. 
@vadoster suggestion will help, but configuration will be lost, so if you want to keep it we recommend to make backup of the configuration first. Also, just for your information you can find previous versions of your configuration in folder “backup” in configuration volume.
Also, to avoid data losing you can keep volume tb-gw-config untouched and the updated image should use it.
Whenever we will take a look at this issue and solve it.

**Comment by franklupo** [comment]
I have problems it freezes and doesn't work

**Comment by franklupo** [comment]
Hi,
i received this error  `|ERROR| - [tcp.py] - tcp - connect - 187 ` and the IotGatewsy doesn't send data anymore.
Restart the container everything restarts.
My version is 3.5.1. 

I have a subcription. How can we resolve the problem?

```
2024-10-10 14:23:08 - |INFO| - [modbus_connector.py] - modbus_connector - run - 804 - {'deviceName': 'IT50 - XXXXXXX', 'deviceType': 'XXXX 96H', 'telemetry': [{'ActiveEnergyAbsorbedLSB': 99715900}, {'ReactiveEnergyAboserbedLSB': 43253800}, {'ActiveEnergyDeliveredLSB': 0}, {'ReactiveEnergyDeliveredLSB': 0}, {'ActivePowerTot': 0}, {'ReactivePowerTot': 0}, {'CosPhiTot': 1000}], 'attributes': []}
2024-10-10 14:23:37 - |ERROR| - [tcp.py] - tcp - connect - 187 - Connection to (10.4.0.70, 502) failed: timed out
```

best regards

**Comment by franklupo** [comment]
Hi,
every 4 days it stops. I have to restart the container. I have a subscription but my client is starting to doubt the system. I want to solve the problem. 
I'm on 3.5.1 and as I already wrote if I switch to 3.5.3 nothing works. 
What is the problem?

best regards
