### ISSUE TITLE
[BUG] AttributeError: module 'signal' has no attribute 'SIGALRM' on Windows machine

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard-gateway#1611]
**Describe the bug**
Cannot run unit tests because of compilation error: 
```
Error
Traceback (most recent call last):
  File "C:\Users\Admin\code\tb\thingsboard-gateway\tests\unit\service\test_duplicate_detector.py", line 96, in setUp
    super().setUp()
  File "C:\Users\Admin\code\tb\thingsboard-gateway\tests\unit\BaseUnitTest.py", line 11, in setUp
    super().setUp()
  File "C:\Users\Admin\code\tb\thingsboard-gateway\tests\base_test.py", line 33, in setUp
    signal.signal(signal.SIGALRM, self._timeout_handler)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by imbeacon** [comment]
Hi @devaskim,

You are right, this signal is not implemented on Windows, we have added check, to avoid usage it on this platform.
