### ISSUE TITLE
Write to OPC UA server fails with No content to map due to end-of-input

### ISSUE THREAD

**Issue by ExPS-Pisko** [thingsboard/thingsboard-gateway#195]
Hi everybody, I have successfully done the mapping of OPC UA Tags to TB, the config looks like this:
{
  "servers": [
    {
      "applicationName": "Thingsboard OPC-UA client",
      "applicationUri": "",
      "host": "127.0.0.1",
      "port": 48020,
      "scanPeriodInSeconds": 1,
      "timeoutInMillis": 5000,
      "security": "None",
      "identity": {
        "type": "anonymous"
      },
      "keystore": {
        "type": "PKCS12",
        "location": "example.pfx",
        "fileContent": "",
        "password": "secret",
        "alias": "gateway",
        "keyPassword": "secret"
      },
      "mapping": [
        {
          "deviceNodePattern": "Demo\\.Static+$",
          "deviceNamePattern": "New Batch Prep",
          "attributes": [{"key": "Recipe ID","type": "long","value": "${Scalar.Int32}"}, {"key": "BCR Start","type": "boolean","value": "${Scalar.Boolean}"}],
          "timeseries": [{"key": "Serie1","type": "long","value": "${Scalar.Int32}"}]
        },
        {
          "deviceNodePattern": "Demo\\.Dynamic+$",
          "deviceNamePattern": "Filling Stand A",
          "attributes": [],
          "timeseries": [{"key": "PT0211A","type": "double","value": "${Scalar.Int32}"}, {"key": "TT0211A","type": "double","value": "${Scalar.Float}"}]
        }

      ]
    }
  ]
}

but I have no success in writing to OPC UA server through RPC call. I have created a message using Action Generator Rule Node (Originator is of type Device, Name Filling Stand A)
{
    "method": "write",
    "params": {
        "Scalar.Int32": 42,
        "Scalar.Int16": 77
    }
}

The whole TagID in OPC UA Server is Demo.Static.Scalar.Int32 (or .Int16)
metadata are:
{
    "deviceID": "6e72f6f0-a1c8-11e9-bd43-75b485762cbe"
}

Where the string is taken from Filling Stand A device

The message is then passed over to the RPC Call request rule node. The execution always ends up with TIMEOUT ERROR. In tb-gateway.log, I can find the following message:

2019-07-12 23:55:56,982 [pool-1-thread-7] DEBUG o.t.g.e.opc.rpc.RpcProcessor - RPC received: device='Filling Stand A', command=RpcCommandData(requestId=20792, method=write, params=)
2019-07-12 23:55:56,982 [pool-1-thread-7] ERROR o.t.g.s.gateway.MqttGatewayService - [Filling Stand A][20792] Failed to process rpc command
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at org.thingsboard.gateway.util.JsonTools.fromString(JsonTools.java:56)
	at org.thingsboard.gateway.extensions.opc.rpc.RpcProcessor.onRpcCommand(RpcProcessor.java:80)
	at org.thingsboard.gateway.service.gateway.MqttGatewayService.lambda$null$23(MqttGatewayService.java:480)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2861)
	at org.thingsboard.gateway.util.JsonTools.fromString(JsonTools.java:54)
	... 7 common frames omitted

From this I guess that the RPC Call request is passed from Chain-Rules to the TB-Gateway, but the params are missing? No idead what to change even after several days of trying, changing and testing. Can anybody help?

**Comment by zbeacon** [comment]
Hi @ExPS-Pisko,

We have released a new version of the gateway. The new version is python-based, please try to use it for your own purposes. Documentation for the gateway you can find [here](https://thingsboard.io/docs/iot-gateway/getting-started/).
