### ISSUE TITLE
[HELP] OPC-UA connector gives error after some time - concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by Tikarei** [thingsboard/thingsboard-gateway#312]
**Describe the issue**
OPC-UA connector stops working after an intermittent amount of time, usually runs for about 30 minutes before stopping. Restarting the docker container will get it to work again until it crashes again after a certain amount of time.

I have double-checked that the OPC-UA server is not having any disconnects by viewing the subscribed data on another OPC-UA client called UaExpert.

I did some digging and I think it has to do with the Python error:
```concurrent.futures._base.CancelledError```

Any help is greatly appreciated.

**Configuration**
Not attaching since I don't think that's the problem. I have only the OPC-UA connector switched on and the opcua.json is a simple test that is working and pushing data.

**Connector name:**
OPC-UA Connector

**Error traceback from /var/log/thingsboard-gateway/connector.log:**
```
''2020-05-25 06:28:20' - DEBUG - opcua_connector - 504 - [SUBSCRIPTION] Data to ThingsBoard: {'deviceName': 'Device F9FA0168466', 'deviceType': 'default', 'attributes': [], 'telemetry': [{'saw': >
''2020-05-25 06:28:20' - DEBUG - opcua_connector - 498 - Python: New data change event on node Node(StringNodeId(ns=6;s=::Sine:SineValue)), with val: 0.9230247735977173 and data DataChangeNotific>
''2020-05-25 06:28:20' - DEBUG - opcua_connector - 504 - [SUBSCRIPTION] Data to ThingsBoard: {'deviceName': 'Device F9FA0168466', 'deviceType': 'default', 'attributes': [], 'telemetry': [{'sine':>
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 498 - Python: New data change event on node Node(StringNodeId(ns=6;s=::Saw:SawValue)), with val: 70.0 and data DataChangeNotification(<opcua.com>
''2020-05-25 06:28:21' - ERROR - opcua_connector - 464 - Request during search has been canceled by the OPC-UA server.'
''2020-05-25 06:28:21' - INFO - opcua_connector - 196 - OPC-UA Connector has been stopped.'
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 274 - [{'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU': {'deviceNodePattern': 'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU', 'devic>
''2020-05-25 06:28:21' - ERROR - opcua_connector - 154 - '
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/opcua/opcua_connector.py", line 128, in run
    self.client.connect()
  File "/root/.local/lib/python3.8/site-packages/opcua/client/client.py", line 275, in connect
    self.open_secure_channel()
  File "/root/.local/lib/python3.8/site-packages/opcua/client/client.py", line 325, in open_secure_channel
    result = self.uaclient.open_secure_channel(params)
  File "/root/.local/lib/python3.8/site-packages/opcua/client/ua_client.py", line 265, in open_secure_channel
    return self._uasocket.open_secure_channel(params)
  File "/root/.local/lib/python3.8/site-packages/opcua/client/ua_client.py", line 199, in open_secure_channel
    response = struct_from_binary(ua.OpenSecureChannelResponse, future.result(self.timeout))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    raise CancelledError()
concurrent.futures._base.CancelledError
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 498 - Python: New data change event on node Node(StringNodeId(ns=6;s=::Sine:SineValue)), with val: 0.6307642459869385 and data DataChangeNotific>
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 468 - Stop on scanning.'
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 274 - [{'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU': {'deviceNodePattern': 'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU', 'devic>
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 498 - Python: New data change event on node Node(StringNodeId(ns=6;s=::Saw:SawValue)), with val: 75.0 and data DataChangeNotification(<opcua.com>
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 468 - Stop on scanning.'
''2020-05-25 06:28:21' - DEBUG - opcua_connector - 274 - [{'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU': {'deviceNodePattern': 'Root\\.Objects\\.DeviceSet\\.PLC\\.Resources\\.CPU', 'devic>
```

**Versions (please complete the following information):**
 - OS: Docker host is Ubuntu 18.04
 - Thingsboard IoT Gateway version: Docker latest image
 - Python version: Docker host is running Python 2.7.18rc1 and Python 3.8.2. Don't know IoT gateway container version.

**Comment by Tikarei** [comment]
I believe I have solved the problem by pulling the latest [opcua_connector.py](https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/connectors/opcua/opcua_connector.py) code from master.

Also, it seems to have fixed an issue where attributes were not pulling when pulling multiple timeseries data.
