### ISSUE TITLE
[HELP] modbus RPC can't write value "0" on coil

### ISSUE THREAD

**Issue by Lautaro-a** [thingsboard/thingsboard-gateway#464]
I've been trying to control the relay of a device, i managed to turn it on using modbus rpc and control widgets, writing the value "1" on the modbus address 0. But when i tried to write the value "0" to turn it off, i got a request timeout.

Connector: modbus_serial.json
https://gist.githubusercontent.com/Lautaro-a/71ae2c81346217005cdce7fbf1aebc00/raw/60235165691d790cfaea2f91d14db150636b678f/modbus_serial.json

Error traceback:
```
""2021-01-19 15:34:53" - ERROR - [modbus_connector.py] - modbus_connector - 328 - 'value'"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/thingsboard_gateway-2.5.2-py3.5.egg/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 316, in server_side_rpc_handler
    self.__process_rpc_request(content, rpc_command_config)
  File "/usr/local/lib/python3.5/dist-packages/thingsboard_gateway-2.5.2-py3.5.egg/thingsboard_gateway/connectors/modbus/modbus_connector.py", line 338, in __process_rpc_request
    rpc_command_config, content)
  File "/usr/local/lib/python3.5/dist-packages/thingsboard_gateway-2.5.2-py3.5.egg/thingsboard_gateway/connectors/modbus/bytes_modbus_downlink_converter.py", line 51, in convert
    value = config["value"]
```
RPC error Audit Log
https://gist.githubusercontent.com/Lautaro-a/18f8d378b596d0f104cd71320b849759/raw/16dcc630f8d8dd24206c8abedb160fe192f5c99d/RPC%2520error%2520Audit%2520log

Versions:
 - OS: Debian GNU/linux 9.3
 - Thingsboard IoT Gateway version 2.5.2
 - Python version 3.5.3
 - Thingsboard version 3.1.1PE

**Comment by zbeacon** [comment]
Hi @Lautaro-a ,

Thank you for your interest in ThingsBoard IoT gateway. Please try to use the version from master branch.
