### ISSUE TITLE
[HELP] Continue to receive a timeout error. 

### ISSUE THREAD

**Issue by paulpoteat** [thingsboard/thingsboard-gateway#569]
**Describe the issue**
We installed the community version of TB as well as the TB Gateway on Ubuntu 20.04 LTS through EC2 and are constantly receiving the error for socket.timeout: timed out for the MQTT broker. We have port 1883 open along with other ports and have yet to be able to get a mosquito_pub to connect to the MQTT broker. It just gives us a timeout error. The TB server is running just fine with all tenants and devices showing along with the gateway device we setup to get the access token to use. Has anyone seen this error before that can shed some light as to what could be wrong in our setup?

**Configuration** (Attach your configuration file)
thingsboard:
  host: ************ - using a FQDN thats private 
  port: 1883
  remoteShell: false
  remoteConfiguration: false
  statsSendPeriodInSeconds: 3600
  checkConnectorsConfigurationInSeconds: 60
  security:
          accessToken: *********************
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
#  type: file
#  data_folder_path: ./data/
#  max_file_count: 10
#  max_read_records_count: 10
#  max_records_per_file: 10000
connectors:
  - name: MQTT Broker Connector
    type: mqtt
    configuration: mqtt.json

#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus.json
#
#  -
#    name: Modbus Connector
#    type: modbus
#    configuration: modbus_serial.json
#
#  -
#    name: OPC-UA Connector
#    type: opcua

**Connector name (If you need help with some connector/converter):**
MQTT Connector - mqtt_connector.py

**Error traceback (If it was raised):**
""2021-09-10 20:36:15" - INFO - [mqtt_connector.py] - mqtt_connector - 160 - Number of accepted disconnectRequests handlers: 2"
""2021-09-10 20:36:15" - INFO - [mqtt_connector.py] - mqtt_connector - 164 - Number of rejected disconnectRequests handlers: 0"
""2021-09-10 20:36:15" - DEBUG - [mqtt_connector.py] - mqtt_connector - 149 - Mandatory key 'deviceNameFilter' found in attributeUpdates handler: {"deviceNameFilter": "SmartMeter.*", "attributeFilter": "uploadFrequency", "topicExpression": "sensor/${deviceName}/${attributeKey}", "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"}"
""2021-09-10 20:36:15" - DEBUG - [mqtt_connector.py] - mqtt_connector - 149 - Mandatory key 'attributeFilter' found in attributeUpdates handler: {"deviceNameFilter": "SmartMeter.*", "attributeFilter": "uploadFrequency", "topicExpression": "sensor/${deviceName}/${attributeKey}", "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"}"
""2021-09-10 20:36:15" - DEBUG - [mqtt_connector.py] - mqtt_connector - 149 - Mandatory key 'topicExpression' found in attributeUpdates handler: {"deviceNameFilter": "SmartMeter.*", "attributeFilter": "uploadFrequency", "topicExpression": "sensor/${deviceName}/${attributeKey}", "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"}"
""2021-09-10 20:36:15" - DEBUG - [mqtt_connector.py] - mqtt_connector - 149 - Mandatory key 'valueExpression' found in attributeUpdates handler: {"deviceNameFilter": "SmartMeter.*", "attributeFilter": "uploadFrequency", "topicExpression": "sensor/${deviceName}/${attributeKey}", "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"}"
""2021-09-10 20:36:15" - DEBUG - [mqtt_connector.py] - mqtt_connector - 157 - attributeUpdates handler has all mandatory keys => accepted: {"deviceNameFilter": "SmartMeter.*", "attributeFilter": "uploadFrequency", "topicExpression": "sensor/${deviceName}/${attributeKey}", "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"}"
""2021-09-10 20:36:15" - INFO - [mqtt_connector.py] - mqtt_connector - 160 - Number of accepted attributeUpdates handlers: 1"
""2021-09-10 20:36:15" - INFO - [mqtt_connector.py] - mqtt_connector - 164 - Number of rejected attributeUpdates handlers: 0"
""2021-09-10 20:37:15" - ERROR - [mqtt_connector.py] - mqtt_connector - 179 - timed out"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/mqtt/mqtt_connector.py", line 177, in run
    self.__connect()
  File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/mqtt/mqtt_connector.py", line 194, in __connect
    self._client.connect(self.__broker['host'],
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
""2021-09-10 20:37:15" - INFO - [mqtt_connector.py] - mqtt_connector - 210 - MQTT Broker Connector has been stopped."

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Thingsboard IoT Gateway version [e.g. 2.2.4]
 - Python version[e.g. 3.7]

**Comment by paulpoteat** [comment]
this item can be closed we finally figured out that when the TB gateway is installed on the same endpoint as the TB server you have to change the port from 1883 to 1882 and open the port for the MQTT data to be accepted. However there is still an error that is being reported about the MQTT connector timing out but we are looking into it after changing the port and clearing out the logs. So more than likely that error is resolved with the PORT being changed on the TB config file for the MQTT host.
