### ISSUE TITLE
[BUG] Compability issue with paho 1.6.1 version

### ISSUE THREAD

**Issue by l33tkrew** [thingsboard/thingsboard-gateway#675]
**Describe the bug**
When I used the latest paho-mqtt, I got errors. But when I use paho-mqtt 1.5.0 version. I do not get any errors.

* Server with latest master branch version
> Paho version in the master branch has the latest paho-mqtt (1.6.1). When I copy the client.py from paho-mqtt 1.5.0 version on this server's client.py file. The errors go off.

* Server with 2.9 deb package version
> In the deb package installation, paho_mqtt-1.5.0 is installed by default. When I copy the client.py from the 1.6.1 version on this server. The same error occurs. 

I think the master branch version has a compatibility issue with paho-mqtt 1.6.1, which is installed automatically while installing the master branch.
Also, the latest docker image for tb-gateway has also paho-mqtt (1.6.1) installed by default. Therefore, the same errors occur. 

I connect to Thingsboard locally. (not demo and cloud). 2.9 works well but the master branch version does not.

Commands I used: 

```
mosquitto_pub -h "192.168.1.11" -p "1883" -t "/sensor/data" -m '{"serialNumber": "SN-001", "sensorType": "Thermometer", "sensorModel": "T1000", "temp": 42, "hum": 58}'
curl -v -X POST -d "{\"name\":\"DEV-01\",\"sensorModel\":\"snn-01\",\"temp\":33,\"hum\":23}" http://192.168.1.11:5000/device1 -H "Content-Type:application/json"
```

The commands work well in 2.9 deb version. In other words, the gateway can communicate with thingsboard without any problem.  But due to client.py in the master branch version, I got some errors below.

**Connector name (If bug in the some connector):**
MQTT Connector, REST Connector

**Error traceback (If available):**
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/dist-packages/paho_mqtt-1.6.1-py3.8.egg/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/dist-packages/thingsboard_gateway-2.9-py3.8.egg/thingsboard_gateway/tb_client/tb_gateway_mqtt.py", line 79, in _on_message
    self._on_decoded_message(content, message)
  File "/usr/local/lib/python3.8/dist-packages/thingsboard_gateway-2.9-py3.8.egg/thingsboard_gateway/tb_client/tb_gateway_mqtt.py", line 97, in _on_decoded_message
    target = content["device"] + "|*"
KeyError: 'device'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [master branch]
 - Python version[e.g. 3.8]

**Comment by zbeacon** [comment]
Hi @l33tkrew ,

We have released the new version, please try to use it.
