### ISSUE TITLE
[BUG] Docker image error

### ISSUE THREAD

**Issue by l33tkrew** [thingsboard/thingsboard-gateway#676]
**Describe the bug**
I am getting an error while installing the latest docker image. Due to this error, this docker container does not start.

my docker-compose file content;
```
version: '3.0'
services:
  tb-gateway:
    restart: always
    image: "thingsboard/tb-gateway"
    # Ports (Required for REST connector)
    ports:
      - "5000:5000"
    volumes:
      - ~/.tb-gateway/config:/thingsboard_gateway/config
      - ~/.tb-gateway/logs:/thingsboard_gateway/logs
      - ~/.tb-gateway/extensions:/thingsboard_gateway/extensions
```
I created the necessary directories and set permission.

I was able to install thingsboard/tb-gateway:2.0 but 3.0 image version causes an error.

**Connector name (If bug in the some connector):**
-

**Error traceback (If available):**
```
> Executing task: docker logs --tail 1000 -f 836e0bad18d861cf25ea170324f16fee69b2a73edd71bb5b1d60c10e1090ac03 <

Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
```

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [docker latest]
 - Python version[e.g. 3.8]

**Comment by l33tkrew** [comment]
I tried Dockerfile in master branch on github. 

I again got the following errors

```
Removing intermediate container ac8c9391ede3
 ---> 893ec9d889c3
Step 10/12 : RUN mkdir -p /default-config/config /default-config/extensions/ && cp -r /thingsboard_gateway/config/* /default-config/config/ && cp -r /thingsboard_gateway/extensions/* /default-config/extensions
 ---> Running in c052badfff7e
cp: cannot stat '/thingsboard_gateway/config/*': No such file or directory
The command '/bin/sh -c mkdir -p /default-config/config /default-config/extensions/ && cp -r /thingsboard_gateway/config/* /default-config/config/ && cp -r /thingsboard_gateway/extensions/* /default-config/extensions' returned a non-zero code: 1
```

**Comment by zbeacon** [comment]
Hi @l33tkrew ,

It may be caused by one bug, we have updated docker image. Please try to download latest docker image and run again.

**Comment by zhuyujie1993** [comment]
Please provide the source address of docker warehouse.
I tried “ https://registry.hub.docker.com/r/thingsboard/tb-gateway”

Retry or fail to start

**Comment by zhuyujie1993** [comment]
> Hi @l33tkrew ,
> 
> It may be caused by one bug, we have updated docker image. Please try to download latest docker image and run again.

Please provide the source address of docker warehouse.
I tried “ https://registry.hub.docker.com/r/thingsboard/tb-gateway”

Retry or fail to start

**Comment by zhuyujie1993** [comment]
> Hi @l33tkrew ,
> 
> It may be caused by one bug, we have updated docker image. Please try to download latest docker image and run again.

OS：linux/arm64

**Comment by tianke3477** [comment]
have same error in centos7.9

**Comment by l33tkrew** [comment]
It is still the same. I cannot start tb-gateway. I installed the latest version with both docker pull and docker-compose. They gave same error.

You can see it is not starting.
```
18783c0d520c   thingsboard/tb-gateway   "/bin/sh ./start-gat…"   3 days ago   Restarting (1) 5 seconds ago                                                                                          tb-gateway
```

Log
```
Traceback (most recent call last):
  File "//./thingsboard_gateway/tb_gateway.py", line 17, in <module>
    from thingsboard_gateway.gateway.tb_gateway_service import TBGatewayService
ModuleNotFoundError: No module named 'thingsboard_gateway'
```

**Comment by greg-mcnamara** [comment]
@zbeacon I have the same error, see #685. Sorry I didn't see this issue earlier, didn't mean to duplicate.

**Comment by zbeacon** [comment]
Hi, Please try to use the latest docker image now.

**Comment by greg-mcnamara** [comment]
Hi @zbeacon the latest image works for me now. Thanks!
